/** Original, MIT-licensed examples. Never add customer documents to the public site. */
import { buildWordDocumentFixture } from '../../../packages/word/test/document-fixture.ts';
import { buildWorkbookFixture } from '../../../packages/sheets/test/workbook-fixture.ts';

const w = 'http://schemas.openxmlformats.org/wordprocessingml/2006/main';
const r = 'http://schemas.openxmlformats.org/officeDocument/2006/relationships';
const a = 'http://schemas.openxmlformats.org/drawingml/2006/main';
const wp = 'http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing';
const pic = 'http://schemas.openxmlformats.org/drawingml/2006/picture';
const s = 'http://schemas.openxmlformats.org/spreadsheetml/2006/main';
const paragraph = (text: string, size = 22, bold = false, color = '273C2F') => `<w:p><w:pPr><w:spacing w:after="180"/></w:pPr><w:r><w:rPr><w:rFonts w:ascii="Arial" w:hAnsi="Arial"/><w:sz w:val="${size}"/><w:color w:val="${color}"/>${bold ? '<w:b/>' : ''}</w:rPr><w:t>${text}</w:t></w:r></w:p>`;
const section = (landscape = false) => `<w:sectPr><w:pgSz w:w="${landscape ? 15840 : 12240}" w:h="${landscape ? 12240 : 15840}"/><w:pgMar w:top="1080" w:right="1080" w:bottom="1080" w:left="1080"/></w:sectPr>`;
const document = (body: string) => `<w:document xmlns:w="${w}" xmlns:r="${r}" xmlns:a="${a}" xmlns:wp="${wp}" xmlns:pic="${pic}"><w:body>${body}</w:body></w:document>`;
const table = `<w:tbl><w:tblPr><w:tblW w:w="9600" w:type="dxa"/></w:tblPr><w:tblGrid><w:gridCol w:w="3200"/><w:gridCol w:w="3200"/><w:gridCol w:w="3200"/></w:tblGrid>${[['Milestone', 'Owner', 'Status'], ['Prototype', 'Design', 'Complete'], ['Document review', 'Engineering', 'In progress'], ['Release', 'Team', 'Planned']].map((row, i) => `<w:tr>${row.map(text => `<w:tc><w:tcPr><w:tcW w:w="3200" w:type="dxa"/></w:tcPr>${paragraph(text, 20, i === 0)}</w:tc>`).join('')}</w:tr>`).join('')}</w:tbl>`;
const illustration = `<svg xmlns="http://www.w3.org/2000/svg" width="640" height="100" viewBox="0 0 640 100"><rect width="640" height="100" fill="#eff5f0"/><path d="M35 69H605" stroke="#b9d0bf"/><path d="M35 68L140 58L250 62L360 37L470 43L605 20" fill="none" stroke="#477a56" stroke-width="3"/><g fill="#477a56"><circle cx="35" cy="68" r="4"/><circle cx="140" cy="58" r="4"/><circle cx="250" cy="62" r="4"/><circle cx="360" cy="37" r="4"/><circle cx="470" cy="43" r="4"/><circle cx="605" cy="20" r="4"/></g></svg>`;
const drawing = `<w:p><w:r><w:drawing><wp:inline><wp:extent cx="6096000" cy="952500"/><wp:docPr id="1" name="Progress illustration" descr="A rising progress line across six milestones"/><a:graphic><a:graphicData uri="${pic}"><pic:pic><pic:blipFill><a:blip r:embed="progress"/></pic:blipFill></pic:pic></a:graphicData></a:graphic></wp:inline></w:drawing></w:r></w:p>`;
const brief = buildWordDocumentFixture({
  documentXml: document(paragraph('FIELDNOTES / PROJECT 01', 18, true, '608069') + paragraph('A quieter workspace', 44, true) + paragraph('Project brief · September 2026', 20, false, '608069') + paragraph('The goal', 28, true) + paragraph('Build a small place to think, write, and work with documents. Keep the interface quiet and make the content easy to read.') + paragraph('Working principles', 28, true) + paragraph('Give each control a clear purpose. Preserve familiar document layouts. Keep opening, editing, and exporting files close at hand.') + paragraph('Delivery plan', 28, true) + table + paragraph('Progress at a glance', 28, true) + drawing + paragraph('This is an original sample document. Switch to Edit to try a change, then download your own copy.', 20, false, '608069') + section()),
  relationships: [{ id: 'progress', type: `${r}/image`, target: 'media/progress.svg' }],
  parts: [{ itemName: 'word/media/progress.svg', contentType: 'image/svg+xml', xml: illustration }]
});
const mixed = buildWordDocumentFixture({ documentXml: document(paragraph('Portrait and landscape', 40, true) + paragraph('Page one is portrait. The next section is landscape, so the scrollable surface must account for a wider page even before it is visible.') + paragraph('Left edge is reachable. The sentence starts here and remains readable in a narrow pane.') + `<w:p><w:pPr>${section()}</w:pPr><w:r><w:t>Continue to the landscape section below.</w:t></w:r></w:p>` + paragraph('A wider view', 40, true) + paragraph('This landscape section tests horizontal scrolling. Both the left and right page margins should be reachable.') + table + section(true)) });
const stringCell = (ref: string, text: string, style = 0) => `<c r="${ref}" t="inlineStr" s="${style}"><is><t>${text}</t></is></c>`;
const numberCell = (ref: string, value: number) => `<c r="${ref}"><v>${value}</v></c>`;
const formulaCell = (ref: string, formula: string, value: number) => `<c r="${ref}"><f>${formula}</f><v>${value}</v></c>`;
const styles = `<styleSheet xmlns="${s}"><fonts count="2"><font><sz val="11"/><name val="Arial"/></font><font><b/><sz val="11"/><name val="Arial"/><color rgb="FF244B31"/></font></fonts><fills count="3"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="gray125"/></fill><fill><patternFill patternType="solid"><fgColor rgb="FFE6F0E8"/><bgColor indexed="64"/></patternFill></fill></fills><borders count="1"><border/></borders><cellStyleXfs count="1"><xf/></cellStyleXfs><cellXfs count="2"><xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0"/><xf numFmtId="0" fontId="1" fillId="2" borderId="0" xfId="0" applyFont="1" applyFill="1"/></cellXfs></styleSheet>`;
const budget = buildWorkbookFixture({ stylesXml: styles, sheets: [
  { name: 'Budget', sheetId: 1, relationshipId: 'budget', xml: `<worksheet xmlns="${s}"><dimension ref="A1:D9"/><sheetViews><sheetView workbookViewId="0"><pane ySplit="1" topLeftCell="A2" activePane="bottomLeft" state="frozen"/></sheetView></sheetViews><cols><col min="1" max="1" width="28" customWidth="1"/><col min="2" max="4" width="17" customWidth="1"/></cols><sheetData><row r="1">${['Item','Quantity','Unit cost','Total'].map((v,i)=>stringCell(`${'ABCD'[i]}1`,v,1)).join('')}</row>${[['Research', 12, 85], ['Design', 18, 95], ['Engineering', 32, 110], ['Review', 6, 85], ['Hosting', 12, 20]].map(([item,quantity,price],i)=>`<row r="${i+2}">${stringCell(`A${i+2}`,String(item))}${numberCell(`B${i+2}`,Number(quantity))}${numberCell(`C${i+2}`,Number(price))}${formulaCell(`D${i+2}`,`B${i+2}*C${i+2}`,Number(quantity)*Number(price))}</row>`).join('')}<row r="8">${stringCell('A8','Project total',1)}${formulaCell('D8','SUM(D2:D6)',7000)}</row></sheetData></worksheet>` },
  { name: 'Notes', sheetId: 2, relationshipId: 'notes', xml: `<worksheet xmlns="${s}"><cols><col min="1" max="1" width="70" customWidth="1"/></cols><sheetData><row r="1">${stringCell('A1','About this workbook',1)}</row><row r="2">${stringCell('A2','Edit quantities or rates to recalculate the budget.')}</row><row r="3">${stringCell('A3','Use the formula bar to enter formulas beginning with =.')}</row><row r="4">${stringCell('A4','Original MIT-licensed Tumbler sample. Amounts are illustrative.')}</row></sheetData></worksheet>` }
] });
for (const [name, bytes] of [['project-brief.docx', brief], ['mixed-pages.docx', mixed], ['project-budget.xlsx', budget]] as const) {
  await Bun.write(new URL(`../static/samples/${name}`, import.meta.url), bytes);
  console.log(`Generated ${name}`);
}
