import { test, expect } from '@playwright/test';
import { readFile } from 'node:fs/promises';
import { openWordArtifact, wordParagraphText } from '@tumblerjs/word';

test('resize an embedded drawing at reduced zoom, undo, redo, and export its dimensions', async ({ page }) => {
  await page.goto('/playground/word-brief');
  await expect(page.getByText('A quieter workspace', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Edit', exact: true }).click();
  await page.getByLabel('Zoom', { exact: true }).selectOption('0.75');
  const drawing = page.getByRole('button', { name: 'Select A rising progress line across six milestones', exact: true });
  await drawing.click();
  const before = (await drawing.boundingBox())!;
  const handle = page.getByRole('button', { name: 'Resize drawing', exact: true });
  const box = (await handle.boundingBox())!;
  await page.mouse.move(box.x + box.width / 2, box.y + box.height / 2);
  await page.mouse.down();
  await page.mouse.move(box.x - 100, box.y - 15, { steps: 8 });
  await page.mouse.up();
  await expect(page.getByText('Modified locally', { exact: true })).toBeVisible();
  await expect.poll(async () => (await drawing.boundingBox())!.width).toBeLessThan(before.width - 50);
  const resized = (await drawing.boundingBox())!;
  expect(resized.width / resized.height).toBeCloseTo(before.width / before.height, 2);
  await page.getByRole('button', { name: 'Undo', exact: true }).click();
  await expect.poll(async () => (await drawing.boundingBox())!.width).toBeCloseTo(before.width, 0);
  await page.getByRole('button', { name: 'Redo', exact: true }).click();
  await expect.poll(async () => (await drawing.boundingBox())!.width).toBeCloseTo(resized.width, 0);
  const downloadPromise = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Download', exact: false }).click();
  const download = await downloadPromise;
  const artifact = openWordArtifact(new Uint8Array(await readFile((await download.path())!)));
  const exported = [...artifact.document.drawings.values()][0]!;
  expect(exported.widthPoints * 4 / 3 * 0.75).toBeCloseTo(resized.width, 0);
  expect(exported.heightPoints * 4 / 3 * 0.75).toBeCloseTo(resized.height, 0);
  await page.getByRole('button', { name: 'View', exact: true }).click();
  await expect(handle).toHaveCount(0);
});

test('drawing resize can be cancelled and adjusted with the keyboard', async ({ page }) => {
  await page.goto('/playground/word-brief');
  await expect(page.getByText('A quieter workspace', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Edit', exact: true }).click();
  const drawing = page.getByRole('button', { name: 'Select A rising progress line across six milestones', exact: true });
  await drawing.click();
  const before = (await drawing.boundingBox())!;
  const handle = page.getByRole('button', { name: 'Resize drawing', exact: true });
  const box = (await handle.boundingBox())!;
  await page.mouse.move(box.x + box.width / 2, box.y + box.height / 2);
  await page.mouse.down();
  await page.mouse.move(box.x - 100, box.y - 15, { steps: 5 });
  await page.keyboard.press('Escape');
  await page.mouse.up();
  await expect.poll(async () => (await drawing.boundingBox())!.width).toBeCloseTo(before.width, 0);
  await expect(page.getByText('Local preview', { exact: true })).toBeVisible();
  await drawing.click();
  await handle.focus();
  await page.keyboard.press('ArrowLeft');
  await expect.poll(async () => (await drawing.boundingBox())!.width).toBeCloseTo(before.width - 4 / 3, 0);
  await page.getByRole('button', { name: 'Undo', exact: true }).click();
  await expect.poll(async () => (await drawing.boundingBox())!.width).toBeCloseTo(before.width, 0);
});

test('drawings move on the page, resize from the opposite corner, and retain exported placement', async ({ page }) => {
  await page.goto('/playground/word-brief');
  await expect(page.getByText('A quieter workspace', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Edit', exact: true }).click();
  await page.getByLabel('Zoom', { exact: true }).selectOption('0.75');
  const drawing = page.getByRole('button', { name: 'Select A rising progress line across six milestones', exact: true });
  await drawing.click();
  await page.getByLabel('Drawing layout', { exact: true }).selectOption('front');
  const position = () => drawing.evaluate(element => {
    const rect = element.getBoundingClientRect();
    const parent = element.closest('.word-page-content')!.getBoundingClientRect();
    return { x: rect.x - parent.x, y: rect.y - parent.y, width: rect.width, height: rect.height };
  });
  const before = await position();
  const rect = (await drawing.boundingBox())!;
  await page.mouse.move(rect.x + rect.width / 2, rect.y + rect.height / 2);
  await page.mouse.down();
  await page.mouse.move(rect.x + rect.width / 2 + 30, rect.y + rect.height / 2 + 40, { steps: 8 });
  await page.mouse.up();
  await expect(page.getByLabel('Drawing layout', { exact: true })).toHaveValue('front');
  await expect.poll(async () => (await position()).x).toBeCloseTo(before.x + 30, 0);
  await expect.poll(async () => (await position()).y).toBeCloseTo(before.y + 40, 0);
  const moved = await position();
  const topLeft = (await page.getByRole('button', { name: 'Resize drawing top left', exact: true }).boundingBox())!;
  await page.mouse.move(topLeft.x + topLeft.width / 2, topLeft.y + topLeft.height / 2);
  await page.mouse.down();
  await page.mouse.move(topLeft.x + 65, topLeft.y + 15, { steps: 8 });
  await page.mouse.up();
  const resized = await position();
  expect(resized.width).toBeLessThan(moved.width - 40);
  expect(resized.x + resized.width).toBeCloseTo(moved.x + moved.width, 0);
  expect(resized.y + resized.height).toBeCloseTo(moved.y + moved.height, 0);
  await page.getByRole('button', { name: 'Undo', exact: true }).click();
  await expect.poll(async () => (await position()).width).toBeCloseTo(moved.width, 0);
  const downloadPromise = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Download', exact: false }).click();
  const download = await downloadPromise;
  const artifact = openWordArtifact(new Uint8Array(await readFile((await download.path())!)));
  const exported = [...artifact.document.drawings.values()][0]!;
  expect(exported.anchor!.horizontalOffsetPoints).toBeCloseTo(moved.x, 0);
  expect(exported.anchor!.verticalOffsetPoints).toBeCloseTo(moved.y, 0);
  await page.getByLabel('Drawing layout', { exact: true }).selectOption('behind');
  await expect(page.locator('[data-word-drawing]')).toHaveClass(/behind/);
  await page.getByLabel('Drawing layout', { exact: true }).selectOption('inline');
  await expect(page.getByLabel('Drawing layout', { exact: true })).toHaveValue('inline');
});


test('inline dragging moves into text without changing layout and can be undone', async ({ page }) => {
  await page.goto('/playground/word-brief');
  await expect(page.getByText('A quieter workspace', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Edit', exact: true }).click();
  await page.getByLabel('Zoom', { exact: true }).selectOption('0.75');
  const drawing = page.getByRole('button', { name: 'Select A rising progress line across six milestones', exact: true });
  await drawing.click();
  const original = (await drawing.boundingBox())!;
  const destination = page.getByText('Progress at a glance', { exact: true });
  await destination.scrollIntoViewIfNeeded();
  const target = (await destination.boundingBox())!;
  const source = (await drawing.boundingBox())!;
  await page.mouse.move(source.x + source.width / 2, source.y + source.height / 2);
  await page.mouse.down();
  await page.mouse.move(target.x, target.y + target.height / 2, { steps: 8 });
  await page.mouse.up();
  await expect(page.getByText('Modified locally', { exact: true })).toBeVisible();
  await drawing.click();
  await expect(page.getByLabel('Drawing layout', { exact: true })).toHaveValue('inline');
  const downloadPromise = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Download', exact: false }).click();
  const download = await downloadPromise;
  const artifact = openWordArtifact(new Uint8Array(await readFile((await download.path())!)));
  expect([...artifact.document.drawings.values()][0]!.placement).toBe('inline');
  const paragraph = artifact.document.blocks.find(block => block.kind === 'paragraph' && wordParagraphText(artifact.document, block).includes('Progress at a glance'));
  expect(paragraph?.kind === 'paragraph' && wordParagraphText(artifact.document, paragraph)).toBe('\uFFFCProgress at a glance');
  await page.getByRole('button', { name: 'Undo', exact: true }).click();
  await expect(page.getByText('Local preview', { exact: true })).toBeVisible();
  await drawing.click();
  const handle = (await page.getByRole('button', { name: 'Resize drawing top left', exact: true }).boundingBox())!;
  await page.mouse.move(handle.x + handle.width / 2, handle.y + handle.height / 2);
  await page.mouse.down();
  await page.mouse.move(handle.x + 65, handle.y + 15, { steps: 5 });
  await page.mouse.up();
  await expect(page.getByLabel('Drawing layout', { exact: true })).toHaveValue('inline');
  expect((await drawing.boundingBox())!.width).toBeLessThan(original.width);
});
