export * from './commands.ts';
export * from './formatting.ts';
export * from './images.ts';
export * from './tables.ts';
export * from './table-edits.ts';
export { validateText, validateWordText } from './validation.ts';
export { wordParagraphIdentity } from './paragraph-identity.ts';
export { WordParagraphProjection, type WordParagraphSlice, type WordParagraphPart } from './paragraph-projection.ts';
export { WordTableProjection } from './table-projection.ts';
export { wordPageNumberRange, wordItemAlignment, pageNumberEdit, alignWordItem, type WordPositionedEdit, type WordItemAlignment } from './page-number.ts';
