"""Compile the 74 Office table styles in MS-OE376 §2.1.1343. See MS-NOTICE.md."""
import re, json
from pathlib import Path
from xml.etree import ElementTree as ET
root=Path(__file__).resolve().parent.parent
source=(root/'docs/reference/vendor/markdown/microsoft/[MS-OE376].md').read_text()
ns='http://schemas.openxmlformats.org/drawingml/2006/main'
ET.register_namespace('a',ns)
def clean(block):
    return '\n'.join(line for line in block.splitlines() if not re.match(r'\s*(\d+ / 1027|\[MS-OE376\]|Office Implementation Information|Copyright ©|Release:|Built-In Table Style Name)',line)).replace('\f','')
bases={}
for block in re.findall(r'<a:tblStyle\s[^>]*>[\s\S]*?</a:tblStyle>',source):
    node=ET.fromstring('<root xmlns:a="'+ns+'">'+clean(block)+'</root>')[0]
    bases[node.get('styleId')]=node
section=source.split('The following table lists the 74 total built-in table styles')[1].split('And all base built-in tblStyles')[0]
records=[]
for line in clean(section).splitlines():
    if re.match(r'\s*(No Style,|Themed Style|Light Style|Medium Style|Dark Style)',line):records.append({'name':line[:36].strip(),'left':'','base':'','replace':''})
    if not records:continue
    records[-1]['left']+=line[:36];records[-1]['base']+=line[36:66];records[-1]['replace']+=' '+line[66:]
output={}
for record in records:
    guid=re.search(r'\{[A-Fa-f0-9-]{36}\}',re.sub(r'\s','',record['left'])).group()
    base=re.search(r'\{[A-Fa-f0-9-]{36}\}',re.sub(r'\s','',record['base'])).group()
    node=ET.fromstring(ET.tostring(bases[base]));node.set('styleId',guid);node.set('styleName',record['name'])
    swaps=re.findall(r'(\w+) replaced with (\w+)',record['replace'])
    if record['name'].startswith('Dark Style 2 – Accent'):
        accent=int(re.search(r'Accent (\d)',record['name']).group(1))
        for region in node:
            for color in region.iter('{'+ns+'}schemeClr'):
                if color.get('val')=='dk1':color.set('val','accent'+str(accent+1 if region.tag.endswith('firstRow') else accent))
        last=node.find('a:lastRow/a:tcStyle/a:tcBdr/a:top',{'a':ns})
        if last is not None:
            for color in last.iter('{'+ns+'}schemeClr'):color.set('val','dk1')
    elif guid!=base:
        if len(swaps)!=1:raise ValueError(record)
        before,after=swaps[0]
        for color in node.iter('{'+ns+'}schemeClr'):
            if color.get('val')==before:color.set('val',after)
    for element in node.iter():element.text=None;element.tail=None
    output[guid.upper()]=ET.tostring(node,encoding='unicode')
assert len(output)==74,len(output)
(root/'packages/slides/src/builtin-table-styles.ts').write_text('// Generated from MS-OE376 §2.1.1343; see MS-NOTICE.md.\nexport const builtinTableStyles: Readonly<Record<string,string>> = '+json.dumps(output,separators=(',',':'))+';\n')
a=source.index('Intellectual Property Rights Notice');b=source.index('Revision Summary',a)
notice=clean(source[a:b]).strip()
(root/'packages/slides/MS-NOTICE.md').write_text('# Office built-in table style definitions\n\nCopyright © 2022 Microsoft Corporation.\n\n`src/builtin-table-styles.ts` implements the XML samples and colour substitutions in MS-OE376, revision 2022-08-16, §2.1.1343. Generated by `scripts/generate-presentation-table-styles.py`. The included definitions use the following Microsoft Open Specifications permission, not the repository MIT license.\n\n'+notice+'\n')
print(f'Compiled {len(output)} built-in table styles.')
